// Author https://github.com/yegor-sytnyk/movies-list

export default [
  {
    id: 1,
    host: "kube.lin.home",
    agent_policy: "External Agent Policy ",
    version: "7.17.5",
    rev: 'rev.1',
    CPU: "1.29%",
    memory: "290 MB",
    last_activity: "36 seconds ago",
  },
  {
    id: 2,
    host: "elastic.agent.lin.home",
    agent_policy: "External Agent Policy ",
    rev: 'rev.1',
    version: "7.17.5",
    CPU: "1.29%",
    memory: "290 MB",
    last_activity: "36 seconds ago",
  },
  {
    id: 3,
    host: "kube.lin.home",
    agent_policy: "Fleet Server on ECK policy  rev.3",
    rev: 'rev.1',
    version: "7.17.5",
    CPU: "1.29%",
    memory: "290 MB",
    last_activity: "36 seconds ago",
  },
  {
    id: 4,
    host: "kube.lin.home",
    agent_policy: "External Agent Policy rev .1",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
  {
    id: 5,
    host: "server.agent.lin.home",
    agent_policy: "External Agent Policy rev .1",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
  {
    id: 6,
    host: "fleet.server.lin.home",
    agent_policy: "External Agent Policy rev .1",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
  {
    id: 7,
    host: "kube.lin.home",
    agent_policy: "External Agent Policy rev .1",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
  {
    id: 8,
    host: "kube.lin.home",
    agent_policy: "External Agent ECK policy rev .5",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
  {
    id: 9,
    host: "elastic-agent-6szix",
    agent_policy: "External Agent Policy rev .1",
    version: "7.17.5",
    last_activity: "36 seconds ago",
    CPU: "1.29%",
    memory: "290 MB",
    rev: 'rev.1',
  },
];
